# Generated by Django 4.2.5 on 2023-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='Из данной валюты')),
                ('to_currency', models.CharField(max_length=3, verbose_name='В текущую валюту')),
                ('rate', models.FloatField(verbose_name='Коэффициент')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
